services:
  backend:
    build: backend
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - /home/austin/.cache/huggingface/hub/models--meta-llama--Llama-3.2-3B-Instruct:/root/.cache/huggingface/hub/models--meta-llama--Llama-3.2-3B-Instruct
      - /var/lib/docker/logs/feedback_app/backend:/var/log/backend


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend


  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: